// AUTO-GENERATED by scripts/gen-agent-wallets.mjs — do not edit by hand.
// Public wallet registry for the SentinelOS agent team: each specialist agent
// owns its own Casper account and gets paid SOSC over x402 by the Commander.
// Only PUBLIC material lives here; the secret PEMs are gitignored in keys/agents/.

export interface AgentWallet {
  /** Ed25519 public key hex (01-prefixed). */
  publicKey: string;
  /** Bare 32-byte account hash hex — x402 payTo is '00' + this. */
  accountHash: string;
}

export const AGENT_WALLETS: Record<string, AgentWallet> = {
  risk: {
    publicKey: '01cad43d38096656c32f312ec21d6f4588a8ed13841bc901c0d2d6aa7d9d2b4ff4',
    accountHash: 'ee9e008c7b7821f3418fec23bcdad2e0c0e0d1d2ffa8625a91afac801ce90a2d',
  },
  oracle: {
    publicKey: '012e40757ab9f4b25beaf48788cfce28334f3f4a6d21d8a5bcc436bcab7327fb06',
    accountHash: '3f5d5688ad806c439370a8e3e220d748694060d9b0aac4afa84d602696f076bc',
  },
  analytics: {
    publicKey: '013540ed6f12b45a62719fa3affbc4aa1952c8d59b7fb63f9489427a2f71284d01',
    accountHash: '13b108bf12766e2b56ea986dfd3ca17a6b2db01ba9767cb99cf8afc86e9d7dc6',
  },
  treasury: {
    publicKey: '01475ddc2ce509be0c3067d6cab6bee3af9cee054c44b177b1a1dc84e64cc395f4',
    accountHash: '875970e6eadc17ff0499b345c0606ea1a470df3d33b95ef7e64bcc5718edc459',
  },
  governance: {
    publicKey: '01497f2a682a68637037ab16dabdd6283f50190398ef94c55ead8c58d0e7fc2cd9',
    accountHash: '0c5047eff94115df9c52cc039146c8b970cddba4f0abaeb815ed4a6e73a8df40',
  },
  compliance: {
    publicKey: '0128bfffb1a877c1b9f6581fec6b30213869a2854a43f0c3e3f7e321089124b7a3',
    accountHash: '5a5c613511879edde677e3bace5e389cf15b817a15d9d1cd24b0efa28ba78201',
  },
  liquidity: {
    publicKey: '01ac9e3936811f0dc1ae91c32fb39a1100264fc59e157a69d510f55236a37191ae',
    accountHash: 'fbcd5eac05563141779008d7ecf8aaaf09ff4a5286886f22a4877e64f96d8c95',
  },
  insurance: {
    publicKey: '015994f54a6aa0e7264dca47fcd420597b233aeafae99dddd78e4ca1b6b0acfa8f',
    accountHash: '214d4799408ac7e18b4a363ddc631301957f9aec6290c0afe4cc9ed70fe9b001',
  },
  growth: {
    publicKey: '01d3bfdbd1e7643b4e8b4b750547ccad9a5a1dc47763b26bbe1c49afc0324cbdde',
    accountHash: '8a87e3f0a9c907d81653e36b3ae171a8287de9808a89962330a6f2f2e20a7671',
  },
  community: {
    publicKey: '019eabafeb1d9f3b1ebdb967e47d8381c5062e3f558d603506ed9d7a26a7cc2dda',
    accountHash: 'b1a579059c37c5c7ee1f04b40295f20d1ee70515590fbf3135e08610935f5944',
  },
  legal: {
    publicKey: '01335461542acd47795ce914cef46eff1ca5f8b2b35a5cb27245d10941ff55c264',
    accountHash: 'e054c8cccc63a0e7fdf2c78a4dbd8fd7d1109fff2aa429f5f769ad5255b95081',
  },
};
